version: '2'
services:
  db:
    image: ibmcom/cloudant-developer:latest
    ports:  
      - "30080:80"
    hostname: cloudant
    network_mode: bridge
  pixiedust:
    image: markwatsonatx/pixiedust-python27-spark163-alpine:1.0.6   
    command: bash -c "/usr/import/import.sh && /startup.sh"
    volumes:
      - ./import:/usr/import
      - ./src/data:/usr/data
      - ./src/notebooks:/usr/notebooks
    ports:
      - "38888:8888"
    links:
      - db
    network_mode: bridge
